name: Setup Flutter
description: Setup flutter project and toolchains for subsequent actions.

inputs:
  target:
    description: "The working directory where the Flutter project is located."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Get Flutter SDK version from .fvmrc
      run: |
        if [ -f .fvmrc ]; then
          FLUTTER_VERSION=$(cat .fvmrc | jq -r '.flutter')
          echo "FLUTTER_VERSION=$FLUTTER_VERSION" >> $GITHUB_ENV
        else
          echo ".fvmrc file not found, using latest stable Flutter version."
          echo "FLUTTER_VERSION=3.x" >> $GITHUB_ENV
        fi
      shell: bash
      working-directory: ${{ inputs.target }}

    - name: Install Flutter SDK
      uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # v2.16.0
      with:
        channel: any
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Flutter version
      run: flutter --version
      shell: bash

    - name: Install dependencies
      run: flutter pub get
      shell: bash
      working-directory: ${{ inputs.target }}

    - name: Run build_runner
      run: dart run build_runner build --delete-conflicting-outputs
      shell: bash
      working-directory: ${{ inputs.target }}
