include: package:pedantic_mono/analysis_options.yaml
linter:
  rules:
    one_member_abstracts: false
    avoid_redundant_argument_values: false
    prefer_int_literals: false
    flutter_style_todos: false
    cascade_invocations: false
    unnecessary_parenthesis: false
    sort_pub_dependencies: false
