name: diggify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.0
  json_serializable: ^6.8.0
  pedantic_mono: ^1.27.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
